name: Update Dependabot Pull Request Name

on: 
  pull_request:
  label:
   types: [dependencies, dependabot]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/(): ]+'
        title-template: 'jira-id '
  